
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action OptionsAction;

	private global::Gtk.Action HelpAction;

	private global::Gtk.Action SettingsAction;

	private global::Gtk.Action AboutAction;

	private global::Gtk.VBox vbox1;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.CheckButton uploadOnStop;

	private global::Gtk.HBox uploadOptions;

	private global::Gtk.RadioButton imgur;

	private global::Gtk.RadioButton giphy;

	private global::Gtk.RadioButton gfycat;

	private global::Gtk.Button recordStopBtn;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Label fileSizeLabel;

	private global::Gtk.Label elapsedLabel;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.OptionsAction = new global::Gtk.Action("OptionsAction", global::Mono.Unix.Catalog.GetString("Options"), null, null);
		this.OptionsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Options");
		w1.Add(this.OptionsAction, null);
		this.HelpAction = new global::Gtk.Action("HelpAction", global::Mono.Unix.Catalog.GetString("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Help");
		w1.Add(this.HelpAction, null);
		this.SettingsAction = new global::Gtk.Action("SettingsAction", global::Mono.Unix.Catalog.GetString("Settings"), null, null);
		this.SettingsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Settings");
		w1.Add(this.SettingsAction, null);
		this.AboutAction = new global::Gtk.Action("AboutAction", global::Mono.Unix.Catalog.GetString("About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString("About");
		w1.Add(this.AboutAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Gifuser");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		this.vbox1.BorderWidth = ((uint)(10));
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString("<ui><menubar name='menubar1'><menu name='OptionsAction' action='OptionsAction'><menuitem name='SettingsAction' action='SettingsAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='AboutAction' action='AboutAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add(this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.uploadOnStop = new global::Gtk.CheckButton();
		this.uploadOnStop.CanFocus = true;
		this.uploadOnStop.Name = "uploadOnStop";
		this.uploadOnStop.Label = global::Mono.Unix.Catalog.GetString("Upload on stop");
		this.uploadOnStop.Active = true;
		this.uploadOnStop.DrawIndicator = true;
		this.uploadOnStop.UseUnderline = true;
		this.vbox1.Add(this.uploadOnStop);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.uploadOnStop]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.uploadOptions = new global::Gtk.HBox();
		this.uploadOptions.Name = "uploadOptions";
		this.uploadOptions.Spacing = 6;
		// Container child uploadOptions.Gtk.Box+BoxChild
		this.imgur = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("imgur"));
		this.imgur.CanFocus = true;
		this.imgur.Name = "imgur";
		this.imgur.DrawIndicator = true;
		this.imgur.UseUnderline = true;
		this.imgur.Group = new global::GLib.SList(global::System.IntPtr.Zero);
		this.uploadOptions.Add(this.imgur);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.uploadOptions[this.imgur]));
		w4.Position = 0;
		// Container child uploadOptions.Gtk.Box+BoxChild
		this.giphy = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("giphy"));
		this.giphy.CanFocus = true;
		this.giphy.Name = "giphy";
		this.giphy.DrawIndicator = true;
		this.giphy.UseUnderline = true;
		this.giphy.Group = this.imgur.Group;
		this.uploadOptions.Add(this.giphy);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.uploadOptions[this.giphy]));
		w5.Position = 1;
		// Container child uploadOptions.Gtk.Box+BoxChild
		this.gfycat = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("gfycat"));
		this.gfycat.CanFocus = true;
		this.gfycat.Name = "gfycat";
		this.gfycat.DrawIndicator = true;
		this.gfycat.UseUnderline = true;
		this.gfycat.Group = this.imgur.Group;
		this.uploadOptions.Add(this.gfycat);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.uploadOptions[this.gfycat]));
		w6.Position = 2;
		this.vbox1.Add(this.uploadOptions);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.uploadOptions]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.recordStopBtn = new global::Gtk.Button();
		this.recordStopBtn.CanFocus = true;
		this.recordStopBtn.Name = "recordStopBtn";
		this.recordStopBtn.UseUnderline = true;
		this.recordStopBtn.Label = global::Mono.Unix.Catalog.GetString("Record");
		this.vbox1.Add(this.recordStopBtn);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.recordStopBtn]));
		w8.Position = 3;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.fileSizeLabel = new global::Gtk.Label();
		this.fileSizeLabel.Name = "fileSizeLabel";
		this.hbox2.Add(this.fileSizeLabel);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.fileSizeLabel]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.elapsedLabel = new global::Gtk.Label();
		this.elapsedLabel.Name = "elapsedLabel";
		this.hbox2.Add(this.elapsedLabel);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.elapsedLabel]));
		w10.PackType = ((global::Gtk.PackType)(1));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
		w11.PackType = ((global::Gtk.PackType)(1));
		w11.Position = 4;
		w11.Expand = false;
		w11.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 310;
		this.DefaultHeight = 165;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.SettingsAction.Activated += new global::System.EventHandler(this.OnSettingsActionActivated);
		this.AboutAction.Activated += new global::System.EventHandler(this.OnAboutActionActivated);
		this.uploadOnStop.Toggled += new global::System.EventHandler(this.OnUploadOnStopToggled);
		this.imgur.Toggled += new global::System.EventHandler(this.OnRadioButtonToggled);
		this.giphy.Toggled += new global::System.EventHandler(this.OnRadioButtonToggled);
		this.gfycat.Toggled += new global::System.EventHandler(this.OnRadioButtonToggled);
		this.recordStopBtn.Clicked += new global::System.EventHandler(this.OnRecordStopBtnClicked);
	}
}
